### ISSUE TITLE
Disable Plymouth on CircleCi?

### ISSUE THREAD

**Issue by msenne** [banister/plymouth#15]
The instructions for Travis were to add 
env: USE_PLYMOUTH="no"
to the travis.yml file.  Figuring it would be similar, I added the same line to the end of my circle.yml file, committed, pushed, no luck.

Do I need to nest this env: option inside another setting? Here is my complete circle.yml file, for reference. Any help would be appreciated.

```
machine:
  timezone:
    America/New_York

deployment:
  staging:
    branch: master
    heroku:
      appname: viewabill-staging

env: USE_PLYMOUTH="no"
```
